# This file allows to use a dev env with QtCreator
# Open the CMakeLists.txt in the sources

set(ENABLE_CODECS @COD_OPTIONS_ENABLE@ CACHE BOOL "Enable Codecs" FORCE)
set(DISABLE_BUNDLED_DEPS @COD_DISABLE_BUNDLE_DEPS@ CACHE BOOL "Disable bundle deps" FORCE)

set(OPENELEC ON CACHE BOOL "Embedded Target" FORCE)
set(BUILD_TARGET @BUILD_TARGET@ CACHE STRING "PMP build Target")

set(QTROOT @SYSROOT_PREFIX@/usr/local/qt5)
set(ENABLE_HELPER OFF)

set(CMAKE_VERBOSE_MAKEFILE true)
set(CMAKE_BUILD_TYPE Debug)
set(CMAKE_SYSROOT @SYSROOT_PREFIX@)
set(CMAKE_INSTALL_PREFIX /usr)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
